import { defineConfig } from 'cz-git';

export default defineConfig({
  extends: ['@commitlint/config-conventional'],
  prompt: {
    messages: {
      type: 'Chọn loại commit:',
      scope: 'Chọn phạm vi thay đổi (scope, không bắt buộc):',
      customScope: 'Nhập scope:',
      subject: 'Nhập mô tả ngắn gọn:\n',
      body: 'Nhập mô tả chi tiết (không bắt buộc). Dùng "|" để xuống dòng:\n',
      breaking: 'Nhập Breaking Change (nếu có). Dùng "|" để xuống dòng:\n',
      footerPrefixsSelect: 'Chọn loại Issue liên quan (không bắt buộc):',
      customFooterPrefix: 'Nhập tiền tố Issue:',
      footer: 'Nhập mã Issue (ví dụ: #31, #34):\n',
      generatingByAI: 'Đang tạo tiêu đề commit bằng AI...',
      generatedSelectByAI: 'Chọn tiêu đề commit do AI đề xuất:',
      confirmCommit: 'Bạn có chắc chắn muốn tạo commit này không?',
    },
    types: [
      { value: 'feat', name: 'feat:     ✨  Thêm tính năng mới', emoji: ':sparkles:' },
      { value: 'fix', name: 'fix:      🐛  Sửa lỗi', emoji: ':bug:' },
      { value: 'docs', name: 'docs:     📝  Cập nhật tài liệu', emoji: ':memo:' },
      { value: 'style', name: 'style:    💄  Chỉnh sửa format/code style', emoji: ':lipstick:' },
      { value: 'refactor', name: 'refactor: ♻️   Tái cấu trúc code', emoji: ':recycle:' },
      { value: 'perf', name: 'perf:     ⚡️  Tăng hiệu năng', emoji: ':zap:' },
      { value: 'test', name: 'test:     ✅  Thêm/Sửa test', emoji: ':white_check_mark:' },
      { value: 'build', name: 'build:    📦️   Cập nhật build hoặc dependency', emoji: ':package:' },
      { value: 'ci', name: 'ci:       🎡  Cập nhật CI/CD', emoji: ':ferris_wheel:' },
      { value: 'chore', name: 'chore:    🔨  Công việc khác', emoji: ':hammer:' },
      { value: 'revert', name: 'revert:   ⏪️  Hoàn tác commit', emoji: ':rewind:' },
    ],
    useEmoji: true,
    emojiAlign: 'center',
    useAI: false,
    aiNumber: 1,
    themeColorCode: '',
    scopes: [{ name: 'fe' }, { name: 'be' }],
    allowCustomScopes: true,
    allowEmptyScopes: true,
    customScopesAlign: 'bottom',
    customScopesAlias: 'custom',
    emptyScopesAlias: 'empty',
    upperCaseSubject: null,
    markBreakingChangeMode: false,
    allowBreakingChanges: ['feat', 'fix'],
    breaklineNumber: 100,
    breaklineChar: '|',
    skipQuestions: [],
    issuePrefixes: [{ value: 'closed', name: 'closed:   ISSUES has been processed' }],
    customIssuePrefixAlign: 'top',
    emptyIssuePrefixAlias: 'skip',
    customIssuePrefixAlias: 'custom',
    allowCustomIssuePrefix: true,
    allowEmptyIssuePrefix: true,
    confirmColorize: true,
    scopeOverrides: undefined,
    defaultBody: '',
    defaultIssues: '',
    defaultScope: '',
    defaultSubject: '',
  },
});
